  version: '3'
  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    
    kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    eureka:
        build: eureka/.
        container_name: eureka
        ports:
        - 8761:8761
    gateway:
        build: busBalancer/.
        container_name: gateway
        links:
        - "eureka"
        depends_on:
        - eureka
        environment:
          eureka.client.service-url.defaultZone: http://eureka:8761/eureka
        ports:
        - 8081:8081
    backweb:
      build: .
      container_name: backweb
      environment:
        - spring.kafka.bootstrap-servers=kafka:29092
        - eureka.client.service-url.defaultZone= http://eureka:8761/eureka
      depends_on: 
        - zookeeper
        - kafka
        - eureka
        - gateway
      ports:
        - 8080:8080